name: STM32 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Set up ARM toolchain
        run: |
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Build STM32 project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Convert ELF to BIN, Hex, and S19
        run: |
          cd build
          arm-none-eabi-objcopy -O binary cmake-test.elf cmake-test.bin
          arm-none-eabi-objcopy -O ihex cmake-test.elf cmake-test.hex
          arm-none-eabi-objcopy -O srec cmake-test.elf cmake-test.s19

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: STM32F103-Build
          path: |
            build/*.elf
            build/*.bin
            build/*.hex
            build/*.s19

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
 
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: STM32F103-Build
          path: build

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*"
          generateReleaseNotes: true
