name: STM32 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # CMake 설치 (APT로 설치)
    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    # ARM 툴체인 설치
    - name: Set up ARM toolchain
      run: |
        sudo apt-get install -y gcc-arm-none-eabi

    # CMake 빌드 및 빌드 실행
    - name: Build STM32 project
      run: |
        mkdir build
        cd build
        cmake ..
        make
