name: STM32 Build & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc-arm-none-eabi

      - name: Build STM32 project
        run: |
          cmake --preset Debug
          cmake --build --preset Debug

      - name: Convert ELF to BIN and HEX
        run: |
          arm-none-eabi-objcopy -O binary build/Debug/cmake-test.elf build/Debug/cmake-test.bin
          arm-none-eabi-objcopy -O ihex build/Debug/cmake-test.elf build/Debug/cmake-test.hex

      - name: Upload build artifacts
        if: github.ref_type != 'tag'  # 태그일 때는 release 잡에서 다운로드함
        uses: actions/upload-artifact@v4
        with:
          name: STM32F103-Build
          path: |
            build/Debug/cmake-test.bin
            build/Debug/cmake-test.hex

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Rebuild (태그 푸시된 커밋 기준)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc-arm-none-eabi
          cmake --preset Debug
          cmake --build --preset Debug
          arm-none-eabi-objcopy -O binary build/Debug/cmake-test.elf build/Debug/cmake-test.bin
          arm-none-eabi-objcopy -O ihex build/Debug/cmake-test.elf build/Debug/cmake-test.hex

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: build/Debug/cmake-test.bin,build/Debug/cmake-test.hex
          generateReleaseNotes: true
